### ISSUE TITLE
Search-Replace command not working on gutenberg serialized content

### ISSUE THREAD

**Issue by leila-racke** [wp-cli/search-replace-command#126] opened 2019-08-22 14:09 UTC
I'm not sure if this should be a feature or not, however I did notice when I ran search-replaces, largely for switching domains, it seems to be skipping over the Gutenberg content. I believe it's because this data is serialized in a specific way.

**Comment by schlessera** [comment] 2019-09-09 06:51
Indeed, we cannot simply add automatic unslashing here as it would lead to unexpected results. The general rule for search-replace is to be as strict as possible to avoid unintended changes, even if it means you need to do multiple passes.

However, I think you might be able to solve the above in one go with judicious use of the regex flag family `--regex`. I'm not sure it is worth the effort, though.

Closing this as the behavior is as intended.

**Closed by schlessera** 2019-09-09 06:51 UTC
